### ISSUE TITLE
Kindly mention that AirPortBrcm4360_Injector must be disabled for Big Sur / Monterey

### ISSUE THREAD

**Issue by aydenspringer** [RieGan/Ideapad-S340-15iwl-Hackintosh#1]
This kext must be disabled or else the start will stall (on the troublesome Broadcom cards we have)

As for the SD Card, this kext worked for me on Catalina (still yet to test on Monterey... installing it right now)
https://github.com/cholonam/Sinetek-rtsx
(updated version from a different person)

**Comment by RieGan** [comment]
By default `AirPortBrcmNIC_Injector` is used in this config instead of using `AirPortBrcm4360_Injector`. So there's no problem when using this config on BigSur or Monterey.

Any info regarding your test on SD Card reader? I don't have any SD Card laying around, so I couldn't test it.

**Comment by aydenspringer** [comment]
I am going to close this issue (must have happened when I updated the kexts, I will open another one
